import {DocumentationComponent, SubTitleBox, TextBox, TitleBox} from "@/components/token/Documentation/styled";
import {txDoc} from "@/components/token/Documentation/utils";

export const Documentation = () => {
    return (
        <DocumentationComponent>
            <TitleBox>
                <h3>{txDoc("rulesAnalyses")}</h3>
            </TitleBox>
            <TextBox>
                <p>
                    {txDoc("rulesAnalysesText")}
                </p>
                <p>
                    {txDoc("rulesAnalysesText2")}
                </p>
            </TextBox>
            <SubTitleBox>
                <h3>{txDoc("forNotes")}</h3>
            </SubTitleBox>
            <TextBox>
                <p>
                    {txDoc("forNotesNormal")}
                </p>
                <p></p>
                <p>
                    {txDoc("forNotesAlertN1")}
                </p>
                <p>
                    {txDoc("forNotesBadN1")}
                </p>
                <p></p>
                <p>
                    {txDoc("forNotesAlertN2")}
                </p>
                <p>
                    {txDoc("forNotesBadN2")}
                </p>
                <p>
                    {txDoc("forNotesInterventionN2")}
                </p>
                <p></p>
                <p>
                    {txDoc("forNotesAlertN3")}
                </p>
                <p>
                    {txDoc("forNotesBadN3")}
                </p>
                <p>
                    {txDoc("forNotesInterventionN3")}
                </p>
                <p></p>
                <p>
                    {txDoc("forNotesAlertNSubs")}
                </p>
            </TextBox>
            <SubTitleBox>
                <h3>{txDoc("forFouls")}</h3>
            </SubTitleBox>
            <TextBox>
                <p>
                    {txDoc("forFoulsNormal")}
                </p>
                <p></p>
                <p>
                    {txDoc("forFoulsText")}
                </p>
                <p>
                    {txDoc("forFoulsText2")}
                </p>
                <p>
                    {txDoc("forFoulsText3")}
                </p>
                <p>
                    {txDoc("forFoulsText4")}
                </p>
                <p>
                    {txDoc("forFoulsText5")}
                </p>
                <p>
                    {txDoc("forFoulsText6")}
                </p>
                <p>
                    {txDoc("forFoulsText7")}
                </p>
                <p>
                    {txDoc("forFoulsText8")}
                </p>
                <p></p>
                <p>
                    {txDoc("forFoulsAlertN1")}
                </p>
                <p>
                    {txDoc("forFoulsBadN1")}
                </p>
                <p>
                    {txDoc("forFoulsInterventionN1")}
                </p>
                <p></p>
                <p>
                    {txDoc("forFoulsAlertN2")}
                </p>
                <p>
                    {txDoc("forFoulsBadN2")}
                </p>
                <p>
                    {txDoc("forFoulsInterventionN2")}
                </p>
                <p></p>
                <p>
                    {txDoc("forFoulsInterventionN3")}
                </p>
                <p></p>
                <p>
                    {txDoc("forFoulsInterventionNSubs")}
                </p>
            </TextBox>
        </DocumentationComponent>
    );
};
